### ISSUE TITLE
Feature importance

### ISSUE THREAD

**Issue by AleBitetto** [david-cortes/outliertree#5]
Hi,
I'm interested in using your algorithm for a binary classification problem, with very umbalanced target. So the detected outliers will be the rare class. I could use the isotree algorithm but I'm also interested in the global feature importance so I was thinking if it makes sense to use the occurrence of "suspicious column" of all the detected outliers as a proxy. So the column that is mostly used to detect outliers will be the most important feature and so on. What do you think?

Or you can still use isotree and then apply classical model-agnostic techniques such as SHAP or Permutation Features Importance? Given the nature of randomly chosing the splitting variables I suspect those techniques won't work very well, isn't it?

Thanks in advance

**Comment by david-cortes** [comment]
Not sure I get you.

If you want to artificially define a minority class as "observations flagged as outliers by this software", then the column that gets flagged as outlier would be the important feature, followed by the columns used for defining a cluster in decreasing order (although I don't see why would you want to do such a thing in the first place).

If you want to use this software as an aid in binary classification, it's unlikely to help you or to give you a measure of feature importance for a classifier, because this is aimed at outliers which is not the same thing as a minority class, and the types of outliers that this method detects are few by definition, not easily ranked, and different from the type of outliers that other software detects. You'd likely have better luck with `isotree`.
